# Generated by Django 5.0.6 on 2024-06-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPAccs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client_code',
        ),
        migrations.RemoveField(
            model_name='jewelry',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='jewelry',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='ordercomposition',
            name='jewelry_id',
        ),
        migrations.RemoveField(
            model_name='production',
            name='jewelry_id',
        ),
        migrations.RemoveField(
            model_name='master',
            name='specialization_id',
        ),
        migrations.RemoveField(
            model_name='production',
            name='master_id',
        ),
        migrations.RemoveField(
            model_name='materialusage',
            name='material_id',
        ),
        migrations.RemoveField(
            model_name='materialusage',
            name='production_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='ordercomposition',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='JewelryType',
        ),
        migrations.DeleteModel(
            name='Jewelry',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='MaterialUsage',
        ),
        migrations.DeleteModel(
            name='Production',
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.DeleteModel(
            name='OrderComposition',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
