# Generated by Django 5.0.6 on 2024-06-19 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='jewelry_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.jewelry'),
        ),
        migrations.AlterField(
            model_name='production',
            name='master_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.master'),
        ),
        migrations.AlterField(
            model_name='production',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
